services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend_network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=${LOCALSTACK_SERVICES}
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker-data/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4566:4566"
    networks:
      - backend_network
      - frontend_network

  tutordocs_api:
    build:
      context: ./src
      dockerfile: ./TutorDocs.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - AWS__ServiceURL=${AWS__ServiceURL}
      - AWS__AccessKey=${AWS__AccessKey}
      - AWS__SecretKey=${AWS__SecretKey}
      - AWS__BucketName=${AWS__BucketName}
      - AWS__Region=${AWS__Region}
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
    networks:
      - frontend_network
      - backend_network

 
networks:
  frontend_network:
    driver: bridge

  backend_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data/postgres
