<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>f5e7ebe0-40bb-48a5-ab8d-c5e4748cb1fc</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.7.2"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TutorDocs.Shared\TutorDocs.Shared.csproj" />
    </ItemGroup>

</Project>
